version: '3'
services:
  rabbitmq:
    image: rabbitmq
    container_name: rabbitmq
    restart: always
    ports:
    - 5672:5672
  redis:
    image: redis
    container_name: redis
    restart: always
    command: redis-server --save "" --appendfsync no
    ports:
    - 6379:6379
  elasticsearch:
    image: elasticsearch:7.10.1
    container_name: elasticsearch
    restart: always
    environment:
      - discovery.type=single-node
    ports:
    - 9200:9200
