version: '3'
services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    container_name: es
    environment:
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - ELASTIC_USERNAME=elastic
      - ELASTIC_PASSWORD=mD749g97joQPaFM
      - xpack.security.enabled=true
    ports:
      - "59200:9200"
    restart: always
  redis:
    image: redis
    container_name: redis
    command: redis-server --requirepass mD749g97joQPaFM
    ports:
      - "46379:6379"
    restart: always
  rabbitmq:
    image: rabbitmq
    container_name: rabbitmq
    ports:
      - "35672:5672"
    restart: always
