version: '2'
services:
  nginx:
    image: nginx
    container_name: nginx
    restart: always
    network_mode: host
    environment:
      - NGINX_ENTRYPOINT_QUIET_LOGS=1
      - TZ=Asia/Shanghai
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /root/.acme.sh/powerfulyang.com/:/usr/share/nginx/cert/powerfulyang.com/
      - /root/app/www/:/usr/share/nginx/www/
      - ./404.html:/usr/share/nginx/www/404.html
      - ./conf/:/usr/share/nginx/conf/
    logging:
      driver: gelf
      options:
        gelf-address: udp://localhost:12201
